### ISSUE TITLE
Official support for Moodle 3.8?

### ISSUE THREAD

**Issue by acquaalta** [ualberta-eclass/moodle-block_demostudent#1]
Hi,
Is the plugin officially tested for Moodle 3.8?
On the plugin page (https://moodle.org/plugins/pluginversions.php?plugin=block_demostudent), it's stated that the plugin is tested for 3.7

Thanks in advance :-)

**Comment by royko** [comment]
Just tested the functionality on a site upgraded to Moodle 3.8, and the latest version of the block works fine.  Are you installing the block on Moodle 3.8, or are you upgrading a site with an older Moodle that had the block already installed?  If you are installing fresh in Moodle 3.8, I would appreciate knowing how it goes (good or bad).

Thanks!

**Comment by acquaalta** [comment]
Hi,
I installed the plugin (block) on a fresh Moodle 3.8.0 environment, and it seems to work well.

BTW, afterwards I discovered the following issue that was fixed in Moodle 3.8.1:
[MDL-67327 - Switching "JavaScript Cache" on crashes first.js](https://tracker.moodle.org/browse/MDL-67327)
I don't know if this bug should affect the plugin, and I just didn't notice that.

**Comment by royko** [comment]
Excellent.  Thanks for confirming.  We are also on 3.8.1 now, with no problems.  It's good to know that both upgrade path and fresh install are working.
